name: API-Bawang-SCM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file="${{secrets.GCP_SA_KEY}}"

      - name: Set Google Cloud project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          export_default_credentials: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/crucial-quarter-369308/swagger-api-image:${{ github.sha }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy API \
            --image gcr.io/crucial-quarter-369308/swagger-api-image:${{ github.sha }} \
            --platform managed \
            --region asia-southeast2-a \
            --allow-unauthenticated
