name: API-Bawang-SCM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.5.1
        with:
          export_default_credentials: true

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > "$HOME"/gcloud-sa-key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME"/gcloud-sa-key.json
          gcloud auth activate-service-account --key-file="$HOME"/gcloud-sa-key.json

      - name: Set Google Cloud project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/crucial-quarter-369308/swagger-api-image:${{ github.sha }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy API \
            --image gcr.io/crucial-quarter-369308/swagger-api-image:${{ github.sha }} \
            --platform managed \
            --region asia-southeast2-a \
            --allow-unauthenticated
